# Generated by Django 3.1.2 on 2020-10-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jobOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=60)),
                ('company_email', models.CharField(max_length=60)),
                ('job_title', models.CharField(max_length=155)),
                ('job_description', models.CharField(max_length=255)),
                ('salary', models.IntegerField()),
                ('city', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activate', models.BooleanField(default=True)),
            ],
        ),
    ]
