# Generated by Django 3.1.2 on 2020-10-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='job_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='salary',
            field=models.PositiveIntegerField(),
        ),
    ]
