# Generated by Django 3.1.2 on 2020-10-04 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20201004_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=60)),
                ('company_email', models.CharField(max_length=60)),
            ],
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='company_email',
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='company_name',
        ),
        migrations.AddField(
            model_name='joboffer',
            name='company',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='jobs.company'),
        ),
    ]
